/**
 * Thrown in case .join has been called twice or another function, which depends on it is called before .join.
 * @extends {external:Error}
 * @alias module:errors.JoinCalledError
 */
class JoinCalledError extends Error {
  /**
   * Create a JoinCalledError.
   */
  constructor (isNot) {
    super(`.join() has ${isNot ? 'not ' : ''}been called before`)
    this.name = this.constructor.name
    Error.captureStackTrace(this, this.constructor)
  }
}

module.exports = JoinCalledError
